application: open-reserve
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: templates/static
- url: /resource/.*
  script: resource.app
- url: /user/.*
  script: user.app
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
